### ISSUE TITLE
Always resulting in 0

### ISSUE THREAD

**Issue by Mhiw** [obsidiandynamics/tinyrand#1]
By running the examples provided in the [Crates.io](https://crates.io/crates/tinyrand) page, the result is always the same value (0).

**Comment by ekoutanov** [comment]
Did you seed it?

**Comment by Mhiw** [comment]
Doesn't it get seeded automatically when you create the rand object? If it doesn't do that automatically, I think we solved the problem.

**Comment by ekoutanov** [comment]
No. RNGs typically provide the flexibility to be seeded from a variety of sources and/or user-defined values. The examples also discuss seeding.
